name: instrumental_studying_helper
description: A simple tool to help you study your instrument.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^3.0.1
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.10
  provider: ^6.0.5
  responsive_framework: ^0.2.0
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/metronome.mp3

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#FFF"
    theme_color: "#007aff"
